apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-deploymenteswar
  labels:
    app: demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo
  template:
    metadata:
      labels:
        app: demo
    spec:
      containers:
      - name: demo1
        image: reddyvatticharla/userimage:latest
        ports:
        - containerPort: 80                        
---
apiVersion: v1
kind: Service
metadata:
  name: demo-service
spec:
  # type: ClusterIp
  type: NodePort  
  selector:
    app: demo
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      # 30000-32767
      nodePort: 32767